# Chapter 3

This file is used for the computations used in the LDM book, Chapter 3.

## Urn problem

In [1]:
%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rnd
from domains import household_robot

np.set_printoptions(precision=3)

plt.rc('text', usetex = True)
plt.rc('font', family = 'serif', serif = 'Computer Modern Roman', size = 18)

P = np.array([[.2, .6, .15, .05],[.2, .6, .15, .05],[.05, .15, .6, .2],[.05, .15, .6, .2]])
O = np.array([[1, 0],[0, 1],[1, 0],[0, 1]])

u0 = np.array([[0.125, 0.375, 0.375, 0.125]])

# -- MC prediction

P3 = P.dot(P.dot(P))
print('P^3:')
print(P3)

# -- Compute probability of x1 given x0 = 0 and z1 = b

u = P[0, 1] * P[1, :] + P[0, 3] * P[3, :]
u = u / u.sum()

print('\nP[x | x0 = 0, z1 = b] =', u)

# -- Forward computation

Z = [0, 0, 1]

a = np.diag(O[:, Z[0]]).dot(u0.T)
print('\na_0 =', a)

for t in range(1, 3):
    a = np.diag(O[:, Z[t]]).dot(P.T).dot(a)
    print('a_' + str(t) + ' =', a)
    
print('\nu_2 =', (a/sum(a)).T)

# -- Viterbi

m = (u0 * O[:,Z[0]]).T
print('\nm_0 =', m)

for t in range(1, 3):
    i = (m * P).argmax(axis=0)
    m = O[:,Z[t]] * (m * P).max(axis=0)
    m = m.reshape((4, 1))
    print('m_' + str(t) + ' =', m)
    print('i_' + str(t) + ' =', i)

P^3:
[[ 0.152  0.456  0.294  0.098]
 [ 0.152  0.456  0.294  0.098]
 [ 0.098  0.294  0.456  0.152]
 [ 0.098  0.294  0.456  0.152]]

P[x | x0 = 0, z1 = b] = [ 0.188  0.565  0.185  0.062]

a_0 = [[ 0.125]
 [ 0.   ]
 [ 0.375]
 [ 0.   ]]
a_1 = [[ 0.044]
 [ 0.   ]
 [ 0.244]
 [ 0.   ]]
a_2 = [[ 0.   ]
 [ 0.063]
 [ 0.   ]
 [ 0.051]]

u_2 = [[ 0.     0.552  0.     0.448]]

m_0 = [[ 0.125]
 [ 0.   ]
 [ 0.375]
 [ 0.   ]]
m_1 = [[ 0.025]
 [ 0.   ]
 [ 0.225]
 [ 0.   ]]
i_1 = [0 0 2 2]
m_2 = [[ 0.   ]
 [ 0.034]
 [ 0.   ]
 [ 0.045]]
i_2 = [2 2 2 2]


## Household robot example

In [2]:
P = np.array([[0.0 , 0.5 , 0.5 , 0.0 , 0.0 , 0.0],
              [0.5 , 0.0 , 0.0 , 0.5 , 0.0 , 0.0],
              [0.5 , 0.0 , 0.0 , 0.5 , 0.0 , 0.0],
              [0.0 , 0.5 , 0.0 , 0.0 , 0.5 , 0.0],
              [0.0 , 0.0 , 0.0 , 0.5 , 0.0 , 0.5],
              [0.0 , 0.0 , 0.0 , 0.5 , 0.5 , 0.0]])

aux = household_robot()
O = np.array([aux.o(x='K',a='L'), 
              aux.o(x='P',a='L'),
              aux.o(x='D',a='L'),
              aux.o(x='H1',a='L'), 
              aux.o(x='B',a='L'), 
              aux.o(x='L',a='L')])
print(O)

[[  1.800e-03   4.500e-04   3.420e-02   8.550e-03   2.000e-04   5.000e-05
    3.800e-03   9.500e-04   3.420e-02   8.550e-03   6.498e-01   1.625e-01
    3.800e-03   9.500e-04   7.220e-02   1.805e-02]
 [  1.125e-04   2.138e-03   2.138e-03   4.061e-02   1.250e-05   2.375e-04
    2.375e-04   4.513e-03   2.138e-03   4.061e-02   4.061e-02   7.716e-01
    2.375e-04   4.513e-03   4.513e-03   8.574e-02]
 [  2.025e-03   2.250e-04   3.848e-02   4.275e-03   3.848e-02   4.275e-03
    7.310e-01   8.123e-02   2.250e-04   2.500e-05   4.275e-03   4.750e-04
    4.275e-03   4.750e-04   8.123e-02   9.025e-03]
 [  5.184e-01   5.760e-02   1.296e-01   1.440e-02   5.760e-02   6.400e-03
    1.440e-02   1.600e-03   1.296e-01   1.440e-02   3.240e-02   3.600e-03
    1.440e-02   1.600e-03   3.600e-03   4.000e-04]
 [  2.025e-03   3.848e-02   2.250e-04   4.275e-03   2.250e-04   4.275e-03
    2.500e-05   4.750e-04   3.848e-02   7.310e-01   4.275e-03   8.123e-02
    4.275e-03   8.122e-02   4.750e-04   9.025e-03]
 [  3